import { Level } from '../types';

// вместо номера использовать индекс в масииве
export const levelsArr: Level[] = [
  {
    number: 1,
    description: 'Сhoose plates',
    code: '<plate data-str-num="1" data-el-num="1"></plate><plate data-str-num="2" data-el-num="2"></plate><bento data-str-num="3" data-el-num="3"></bento><plate data-str-num="4" data-el-num="4"></plate><plate data-str-num="5" data-el-num="5"></plate>',
    stringsCode: [
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;bento&gt;&lt;/bento&gt;',
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;plate&gt;&lt;/plate&gt;',
    ],
    elNum: ['1', '2', '3', '4', '5'],
    target: 'plate',
  },
  {
    number: 2,
    description: 'Choose pickles',
    code: '<plate data-str-num="1" data-el-num="1"></plate><pickle data-str-num="2" data-el-num="2"></pickle><plate data-str-num="3,4,5" data-el-num="3"><pickle data-str-num="4" data-el-num="4"></pickle></plate><pickle data-str-num="6" data-el-num="5"></pickle><pickle data-str-num="7" data-el-num="6"></pickle>',
    stringsCode: [
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;pickle&gt;',
      '&lt;plate&gt;',
      '  &lt;pickle&gt;',
      '&lt;/plate&gt;',
      '&lt;pickle&gt;',
      '&lt;pickle&gt;',
    ],
    elNum: ['1', '2', '3', '4', '3', '5', '6'],
    target: 'plate + pickle',
  },
  {
    number: 3,
    description: 'Сhoose small apples and oranges on plates',
    code: '<plate data-str-num="1,2,3" data-el-num="1"><orange class="small" data-str-num="2" data-el-num="2"></orange></plate><plate data-str-num="4,5,6" data-el-num="3"><orange data-str-num="5" data-el-num="4"></orange></plate><apple class="small" data-str-num="7" data-el-num="5"></apple><plate data-str-num="8,9,10" data-el-num="6"><apple class="small" data-str-num="9" data-el-num="7"></apple></plate>',
    stringsCode: [
      '&lt;plate&gt;',
      '  &lt;orange class="small"&gt;',
      '&lt;/plate&gt;',
      '&lt;plate&gt;',
      '  &lt;orange&gt;',
      '&lt;/plate&gt;',
      '&lt;apple class="small"&gt;',
      '&lt;plate&gt;',
      '  &lt;apple class="small"&gt;',
      '&lt;/plate&gt;',
    ],
    elNum: ['1', '2', '1', '3', '4', '3', '5', '6', '7', '6'],
    target: 'plate .small',
  },
  {
    number: 4,
    description: 'Сhoose apples',
    code: '<plate data-str-num="1,2,3" data-el-num="1"><apple data-str-num="2" data-el-num="2"></apple></plate><plate plate data-str-num="4,5,6" data-el-num="3"><apple class="small" data-str-num="5" data-el-num="4"></apple></plate><apple class="small" data-str-num="7" data-el-num="5"></apple><apple data-str-num="8" data-el-num="6"></apple>',
    stringsCode: [
      '&lt;plate&gt;',
      '  &lt;apple&gt;',
      '&lt;/plate&gt;',
      '&lt;plate&gt;',
      '  &lt;apple class="small"&gt;',
      '&lt;/plate&gt;',
      '&lt;apple class="small"&gt;',
      '&lt;apple&gt;',
    ],
    elNum: ['1', '2', '1', '3', '4', '3', '5', '6'],
    target: 'apple:not(.small)',
  },
  {
    number: 5,
    description: 'Сhoose apple and orange',
    code: '<plate data-str-num="1,2,3,4" data-el-num="1"><apple data-str-num="2" data-el-num="2"></apple><apple data-str-num="3" data-el-num="3"></apple></plate><plate data-str-num="5,6,7" data-el-num="4"><apple data-str-num="6" data-el-num="5"></apple></plate><bento data-str-num="8,9,10,11" data-el-num="6"><orange data-str-num="9" data-el-num="7"></orange><orange data-str-num="10" data-el-num="8"></orange></bento><bento data-str-num="12,13,14" data-el-num="9"><orange data-str-num="13" data-el-num="10"></orange></bento>',
    stringsCode: [
      '&lt;plate&gt;',
      '  &lt;apple&gt;',
      '  &lt;apple&gt;',
      '&lt;/plate&gt;',
      '&lt;plate&gt;',
      '  &lt;apple&gt;',
      '&lt;/plate&gt;',
      '&lt;bento&gt;',
      '  &lt;orange&gt;',
      '  &lt;orange&gt;',
      '&lt;/bento&gt;',
      '&lt;bento&gt;',
      '  &lt;orange&gt;',
      '&lt;/bento&gt;',
    ],
    elNum: ['1', '2', '3', '1', '4', '5', '4', '6', '7', '8', '6', '9', '10', '9'],
    target: 'apple:only-child, orange:only-child',
  },
  {
    number: 6,
    description: 'Сhoose pickle on plates and bento',
    code: '<plate data-str-num="1,2,3" data-el-num="1"><pickle data-str-num="2" data-el-num="2"></pickle></plate><bento data-str-num="4,5,6" data-el-num="3"><pickle data-str-num="5" data-el-num="4"></pickle></bento><pickle data-str-num="7" data-el-num="5"></pickle><pickle data-str-num="8" data-el-num="6"></pickle>',
    stringsCode: [
      '&lt;plate&gt;',
      '  &lt;pickle&gt;',
      '&lt;/plate&gt;',
      '&lt;bento&gt;',
      '  &lt;pickle&gt;',
      '&lt;/bento&gt;',
      '&lt;pickle&gt;',
      '&lt;pickle&gt;',
    ],
    elNum: ['1', '2', '1', '3', '4', '3', '5', '6'],
    target: 'plate pickle, bento pickle',
  },
  {
    number: 7,
    description: 'Сhoose empty plates and bento',
    code: '<bento data-str-num="1,2,3" data-el-num="1"><orange data-str-num="2" data-el-num="2"></orange></bento><bento data-str-num="4" data-el-num="3"></bento><plate data-str-num="5" data-el-num="4"></plate><plate data-str-num="6,7,8" data-el-num="5"><apple data-str-num="7" data-el-num="6"></apple></plate>',
    stringsCode: [
      '&lt;bento&gt;',
      '  &lt;orange&gt;',
      '&lt;/bento&gt;',
      '&lt;bento&gt;&lt;/bento&gt;',
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;plate&gt;',
      '  &lt;apple&gt;',
      '&lt;/plate&gt;',
    ],
    elNum: ['1', '2', '1', '3', '4', '5', '6', '5'],
    target: 'plate:empty, bento:empty',
  },
  {
    number: 8,
    description: 'Сhoose plate, bento and orange',
    code: '<plate data-str-num="1" data-el-num="1"></plate><plate data-str-num="2" data-el-num="2"></plate><bento data-str-num="3" data-el-num="3"></bento><bento data-str-num="4" data-el-num="4"></bento><orange data-str-num="5" data-el-num="5"></orange>',
    stringsCode: [
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;plate&gt;&lt;/plate&gt;',
      '&lt;bento&gt;&lt;/bento&gt;',
      '&lt;bento&gt;&lt;/bento&gt;',
      '&lt;orange&gt;&lt;/orange&gt;',
    ],
    elNum: ['1', '2', '3', '4', '5'],
    target: '*:last-of-type',
  },
  {
    number: 9,
    description: 'Сhoose apples and oranges',
    code: '<apple data-str-num="1" data-el-num="1"></apple><plate data-str-num="2,3,4,5" data-el-num="2"><apple data-str-num="3" data-el-num="3"></apple><apple data-str-num="4" data-el-num="4"></apple></plate><bento data-str-num="6,7,8,9" data-el-num="5"><orange data-str-num="7" data-el-num="6"></orange><orange data-str-num="8" data-el-num="7"></orange></bento><orange data-str-num="10" data-el-num="8"></orange>',
    stringsCode: [
      '&lt;apple&gt;',
      '&lt;plate&gt;',
      '  &lt;apple&gt;',
      '  &lt;apple&gt;',
      '&lt;/plate&gt;',
      '&lt;bento&gt;',
      '  &lt;orange&gt;',
      '  &lt;orange&gt;',
      '&lt;/bento&gt;',
      '&lt;orange&gt;',
    ],
    elNum: ['1', '2', '3', '4', '2', '5', '6', '7', '5', '8'],
    target: 'apple:first-child, orange:first-child',
  },
  {
    number: 10,
    description: 'Сhoose apples',
    code: '<apple data-str-num="1" data-el-num="1"></apple><apple data-str-num="2" data-el-num="2"></apple><apple data-str-num="3" data-el-num="3"></apple><apple data-str-num="4" data-el-num="4"></apple><apple data-str-num="5" data-el-num="5"></apple>',
    stringsCode: ['&lt;apple&gt;', '&lt;apple&gt;', '&lt;apple&gt;', '&lt;apple&gt;', '&lt;apple&gt;'],
    elNum: ['1', '2', '3', '4', '5'],
    target: 'apple:nth-of-type(2n+3)',
  },
];
